rg_location                     = "UAE North"
rg_creation                     = "new"
environment                     = "prod"
bu_name                         = "gitex"
tenant_name                     = "ict"
node_app_service_plan_sku       = "P2v2"
node_app_service_plan_os_type   = "Windows"
node_version                    = "~18"
python_app_service_plan_sku     = "P2v2"
python_app_service_plan_os_type = "Linux"
python_version                  = "3.11"
virtual_network_name            = "ict-platform-gitex-prod-vnet-uaen"
subnet_resource_group_name      = "ict-platform-gitex-prod-network-rg"
python_as_subnet_name           = "ict-platform-gitex-prod-pyint-snet-uaen"
current_stack                   = "node"
https_only                      = true
minimum_tls_version             = "1.2"
log_analytics_workspace_id      = "/subscriptions/c8b99861-fdf5-4f0c-8f85-e75b141fca08/resourceGroups/ict-platform-hrbot-shared-monitor-rg/providers/Microsoft.OperationalInsights/workspaces/ict-platform-hrbot-shared-law"
application_type                = "web"
identity_type                   = "UserAssigned"
python_app_tags = {
  "Workload Category"  = "Internal Workloads"
  "Workload Name"      = "Python App Service"
  "Business Unit Code" = "DPS"
  "Tier"               = "Backend"
  "Workload Architype" = "Internal Platform"
  "Environment"        = "Prod"
  "Environment Type"   = "Production"
  "Architecture Type"  = "PaaS"
}
node_app_tags = {
  "Workload Category"  = "Internal Workloads"
  "Workload Name"      = "Node App Service"
  "Business Unit Code" = "DPS"
  "Tier"               = "Frontend"
  "Workload Architype" = "Internal Platform"
  "Environment"        = "Prod"
  "Environment Type"   = "Production"
  "Architecture Type"  = "PaaS"
}
appinsights_profilerfeature_version             = "1.0.0"
appinsights_snapshotfeature_version             = "1.0.0"
applicationinsightsagent_extension_version      = "~2"
diagnosticservices_extension_version            = "~3"
instrumentationengine_extension_version         = "~2"
snapshotdebugger_extension_version              = "1.0.15"
xdt_microsoftapplicationinsights_baseextensions = "enabled"
xdt_microsoftapplicationinsights_mode           = "recommended"
SCM_DO_BUILD_DURING_DEPLOYMENT                  = "false"
uaid_name                                       = "ict-platform-gitex-prod-uaid"
data_resource_group_name                        = "ict-platform-gitex-prod-data-rg"
REACT_APP_API_URL                               = null
OPENAI_API_KEY                                  = null
amount                                          = 1534 
timeGrain                                       = "Monthly"
startDate                                       = "2025-02-01T00:00:00Z"
endDate                                         = "2025-12-31T00:00:00Z"
node_autoscale_min_capacity                     = 1
node_autoscale_max_capacity                     = 5
node_autoscale_default_capacity                 = 2
node_cpu_metric_threshold_increase              = 80
node_cpu_metric_threshold_decrease              = 40
node_scale_action_cooldown                      = "PT5M"
node_statistic                                  = "Average"
node_operator_increase                          = "GreaterThan"
node_operator_decrease                          = "LessThan"
node_time_aggregation                           = "Average"
node_time_grain                                 = "PT1M"
node_time_window                                = "PT5M"
node_increase_scale_action_change_count         = 1
node_decrease_scale_action_change_count         = 1
py_autoscale_min_capacity                       = 1
py_autoscale_max_capacity                       = 5
py_autoscale_default_capacity                   = 2
py_cpu_metric_threshold_increase                = 70
py_cpu_metric_threshold_decrease                = 30
py_scale_action_cooldown                        = "PT5M"
py_statistic                                    = "Average"
py_operator_increase                            = "GreaterThan"
py_operator_decrease                            = "LessThan"
py_time_aggregation                             = "Average"
py_time_grain                                   = "PT1M"
py_time_window                                  = "PT5M"
py_increase_scale_action_change_count           = 1
py_decrease_scale_action_change_count           = 1
