address_space_vnet = ["172.20.4.0/24"]
vnet_tags = {
  "Workload Category"  = "Internal Workloads"
  "Workload Name"      = "Dev Vnet"
  "Tier"               = "Networking"
  "Business Unit Code" = "DPS"
  "Workload Architype" = "Internal Platform"
  "Environment"        = "Dev"
  "Environment Type"   = "Non Production"
  "Architecture Type"  = "IaaS"
}
nsg_tags = {
  "Workload Category"  = "Internal Workloads"
  "Workload Name"      = "Development VM NSG"
  "Business Unit Code" = "DPS"
  "Tier"               = "Networking"
  "Workload Architype" = "Internal Platform"
  "Environment"        = "Dev"
  "Environment Type"   = "Non Production"
  "Architecture Type"  = "IaaS"
}
rt_tags = {
  "Workload Category"  = "Internal Workloads"
  "Workload Name"      = "Spoke Route Table"
  "Business Unit Code" = "DPS"
  "Tier"               = "Networking"
  "Workload Architype" = "Internal Platform"
  "Environment"        = "Dev"
  "Environment Type"   = "Non Production"
  "Architecture Type"  = "IaaS"
}
snet1_address_prefix          = ["172.20.4.0/26"]
subnet_compute_address_prefix = ["172.20.4.160/28"]
subnet2_address_prefix        = ["172.20.4.64/26"]
subnet_pep_address_prefix     = ["172.20.4.128/27"]
rg_location                   = "UAE North"
rg_creation                   = "new"
tenant_name                   = "ict"
environment                   = "dev"
bu_name                       = "hrbot"
location_shortname            = "uaen"
hub_vnet_id                   = "/subscriptions/c8b99861-fdf5-4f0c-8f85-e75b141fca08/resourceGroups/ict-platform-hrbot-hub-network-rg/providers/Microsoft.Network/virtualNetworks/ict-platform-hrbot-hub-vnet-uaen"
hub_rg_name                   = "ict-platform-hrbot-hub-network-rg"
hub_vnet_name                 = "ict-platform-hrbot-hub-vnet-uaen"
dns_server                    = ["172.20.0.4"]
hub_subscription_id           = "c8b99861-fdf5-4f0c-8f85-e75b141fca08"
spoke_subscription_id         = "23c04f75-916a-4128-ae5c-d0e2a5c1d89f"
subnet_mohap_python_address_prefix = ["172.20.4.192/26"]